// frontend/admin/vue-element/src/pages/core/login/components/MfaChallenge.vue
<template>
  <div class="mfa-panel-form">
    <h3 class="mfa-panel-form__title">{{ t("core.login.mfaTitle") }}</h3>
    <p class="mfa-panel-form__desc">{{ t("core.login.mfaDesc") }}</p>
    <el-form ref="mfaFormRef" :model="mfaForm" :rules="mfaRules" size="large" @submit.prevent>
      <el-form-item prop="code">
        <el-input
          v-model.trim="mfaForm.code"
          :placeholder="t('core.login.mfaCodePlaceholder')"
          inputmode="numeric"
          maxlength="6"
          @keyup.enter="handleSubmit"
        >
          <template #prefix>
            <el-icon><Key /></el-icon>
          </template>
        </el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" class="w-full" :loading="loginLoading" @click="handleSubmit">
          {{ t("core.login.mfaVerify") }}
        </el-button>
      </el-form-item>
      <el-form-item>
        <el-button class="w-full" @click="cancelMfa">
          {{ t("core.login.mfaCancel") }}
        </el-button>
      </el-form-item>
    </el-form>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { ElNotification } from "element-plus";
import { useRoute, useRouter } from "vue-router";
import { useAuth } from "@/composables/use-auth";
import { i18n } from "@/core/i18n";
import { useAccessStore } from "@/stores";

const t = i18n.global.t;
const router = useRouter();
const route = useRoute();
const { completeMfaChallenge, loginLoading } = useAuth();
const accessStore = useAccessStore();

const mfaFormRef = ref();
const mfaForm = ref({ code: "" });
const mfaRules = {
  code: [
    { required: true, message: t("core.login.mfaCodeRequired"), trigger: "blur" },
    {
      pattern: /^\d{6}$/,
      message: t("core.login.mfaCodeFormatError"),
      trigger: "blur",
    },
  ],
};

const handleSubmit = async () => {
  if (!accessStore.mfaOperationId) {
    ElNotification({
      title: t("core.authentication.loginFailed"),
      message: t("core.login.mfaNotRequired"),
      type: "error",
    });
    await router.push({ name: "Login" });
    return;
  }
  await mfaFormRef.value?.validate(async (valid: boolean) => {
    if (!valid) return;
    // 验证成功后回到进入登录流程前的原目标页（由 store 登录分支透传）
    const redirect = (route.query.redirect as string) || "";
    const safeRedirect = redirect.startsWith("/") && !redirect.startsWith("//") ? redirect : "";
    const result = await completeMfaChallenge(mfaForm.value.code, async () => {
      if (safeRedirect) await router.replace(safeRedirect);
    });
    if (!result?.userInfo) {
      ElNotification({
        title: t("core.authentication.loginFailed"),
        message: t("core.login.mfaVerifyFailed"),
        type: "error",
      });
    }
  });
};

const cancelMfa = async () => {
  accessStore.mfaOperationId = null;
  await router.push({ name: "Login" });
};
</script>

<style scoped>
.mfa-panel-form {
  width: 100%;
}
.mfa-panel-form__title {
  text-align: center;
  font-size: 20px;
  font-weight: 600;
  margin-bottom: 8px;
}
.mfa-panel-form__desc {
  text-align: center;
  font-size: 13px;
  color: var(--el-text-color-secondary);
  margin-bottom: 24px;
}
.w-full {
  width: 100%;
}
</style>

// frontend/admin/react/src/pages/core/auth/mfa-challenge/index.tsx
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Form, Input, Button, App } from 'antd';
import { SafetyOutlined } from '@ant-design/icons';
import { useAuthStore } from '@/stores';
import { useSearchParams } from 'react-router-dom';

const MfaChallenge: React.FC = () => {
  const { t } = useTranslation('auth');
  const { completeMfaChallenge, loginLoading, mfaOperationId } = useAuthStore();
  const { message } = App.useApp();
  const [submitting, setSubmitting] = useState(false);
  const [searchParams] = useSearchParams();

  // 退出 MFA 挑战：清状态并回登录页
  const cancelMfa = () => {
    useAuthStore.setState({ mfaOperationId: null });
    window.location.href = '/auth/login';
  };

  const handleSubmit = async (values: { totpCode: string }) => {
    if (!mfaOperationId) {
      message.error(t('mfaNotRequired'));
      window.location.href = '/auth/login';
      return;
    }
    setSubmitting(true);
    // 验证成功后回到进入登录流程前的原目标页（由登录 store 整页跳转时透传）
    const redirect = searchParams.get('redirect') || '';
    const safeRedirect =
      typeof redirect === 'string' && redirect.startsWith('/') && !redirect.startsWith('//')
        ? redirect
        : '';
    try {
      await completeMfaChallenge(values.totpCode, () => {
        if (safeRedirect) {
          window.location.href = safeRedirect;
        }
      });
    } catch (error: any) {
      message.error(error?.message || t('mfaVerifyFailed'));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 p-4">
      <div className="w-full max-w-md rounded-xl border border-white/10 bg-white/5 p-8 shadow-[0_8px_32px_rgba(0,0,0,0.3)] backdrop-blur-md light:border-gray-100 light:bg-white light:shadow-lg">
        <h2 className="mb-2 text-center text-xl font-semibold text-white light:text-gray-900">
          {t('mfaChallengeTitle')}
        </h2>
        <p className="mb-6 text-center text-sm text-gray-300 light:text-gray-500">
          {t('mfaChallengeDesc')}
        </p>
        <Form name="mfa-challenge" onFinish={handleSubmit} size="large">
          <Form.Item
            name="totpCode"
            rules={[
              { required: true, message: t('mfaCodeRequired') },
              {
                pattern: /^\d{6}$/,
                message: t('mfaCodeFormatError'),
              },
            ]}
          >
            <Input
              prefix={<SafetyOutlined />}
              placeholder={t('mfaCodePlaceholder')}
              autoComplete="one-time-code"
              inputMode="numeric"
              maxLength={6}
            />
          </Form.Item>
          <Form.Item>
            <Button
              type="primary"
              htmlType="submit"
              block
              loading={submitting || loginLoading}
            >
              {t('mfaVerify')}
            </Button>
          </Form.Item>
          <Form.Item>
            <Button block onClick={cancelMfa}>
              {t('mfaCancel')}
            </Button>
          </Form.Item>
        </Form>
      </div>
    </div>
  );
};

export default MfaChallenge;
