// frontend/admin/vue-element/src/pages/app/log/redis_cache_monitor/index.vue
<template>
  <div class="redis-cache-monitor-page">
    <template v-if="isLoading">
      <el-card shadow="hover" class="mb-4">
        <el-empty :description="$t('common.loading')" />
      </el-card>
    </template>
    <template v-else>
    <el-card shadow="hover" class="mb-4">
      <template #header>
        <span class="card-title">{{ $t("pages.redis_cache_monitor.dbSizeCardTitle") }}</span>
      </template>
      <el-descriptions :column="1" border>
        <el-descriptions-item :label="$t('pages.redis_cache_monitor.dbSize')">
          <el-tag :type="dbSize > 0 ? 'warning' : 'info'">{{ String(dbSize) }}</el-tag>
        </el-descriptions-item>
      </el-descriptions>
    </el-card>

    <template v-if="sections.length === 0">
      <el-card shadow="hover" class="mb-4">
        <template #header>
          <span class="card-title">{{ $t("pages.redis_cache_monitor.infoCardTitle") }}</span>
        </template>
        <el-empty :description="$t("pages.redis_cache_monitor.noInfo')" />
      </el-card>
    </template>
    <template v-else>
      <el-card
        v-for="(section, idx) in sections"
        :key="`${section.name}-${idx}`"
        shadow="hover"
        class="mb-4"
      >
        <template #header>
          <div class="section-header" @click="toggleSection(`${section.name}-${idx}`)">
            <span class="card-title">{{ section.name }}</span>
            <el-tag>{{ section.entries.length }}</el-tag>
            <span class="toggle-hint">
              {{
                expandedSections[`${section.name}-${idx}`]
                  ? $t("pages.redis_cache_monitor.collapse")
                  : $t("pages.redis_cache_monitor.expand")
              }}
            </span>
          </div>
        </template>
        <template v-if="expandedSections[`${section.name}-${idx}`]">
          <template v-if="section.entries.length === 0">
            <el-empty :description="$t("pages.redis_cache_monitor.noEntries") />
          </template>
          <template v-else>
            <el-descriptions :column="1" border>
              <el-descriptions-item
                v-for="(entry, eIdx) in section.entries"
                :key="eIdx"
                :label="entry.key"
              >
                <span class="entry-value">{{ entry.value }}</span>
              </el-descriptions-item>
            </el-descriptions>
          </template>
        </template>
        <template v-else>
          <el-empty :description="$t("pages.redis_cache_monitor.collapsed") />
        </template>
      </el-card>
    </template>

    <el-card shadow="hover">
      <template #header>
        <span class="card-title">{{ $t("pages.redis_cache_monitor.slowlogCardTitle") }}</span>
      </template>
      <el-table :data="slowlog" border stripe>
        <el-table-column
          prop="id"
          :label="$t('pages.redis_cache_monitor.slowlogId')"
          width="80"
        />
        <el-table-column
          :label="$t('pages.redis_cache_monitor.createdAt')"
          width="180"
        >
          <template #default="{ row }">
            {{ formatDateTime(row.createdAt ?? "") }}
          </template>
        </el-table-column>
        <el-table-column
          prop="durationUsec"
          :label="$t('pages.redis_cache_monitor.durationUsec')"
          width="120"
        />
        <el-table-column
          prop="clientAddr"
          :label="$t('pages.redis_cache_monitor.clientAddr')"
          width="200"
        />
        <el-table-column
          prop="clientName"
          :label="$t('pages.redis_cache_monitor.clientName')"
          width="120"
        />
        <el-table-column
          :label="$t('pages.redis_cache_monitor.args')"
        >
          <template #default="{ row }">
            <span class="args-cell">{{ (row.args ?? []).join(" ") || "-" }}</span>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <div class="disclaimer">{{ $t("pages.redis_cache_monitor.disclaimer") }}</div>
    </template>
  </div>
</template>

<script lang="ts" setup>
import { ref, computed } from "vue";
import { formatDateTime } from "@/utils";
import { $t } from "@/core/i18n";
import { useRedisCacheMonitorInfo } from "@/api/composables";
import type {
  redis_cacheservicev1_RedisCacheMonitorInfo,
  redis_cacheservicev1_InfoSection,
  redis_cacheservicev1_SlowLogEntry,
} from "@/api/generated/admin/service/v1";

const { data, isLoading } = useRedisCacheMonitorInfo();

const expandedSections = ref<Record<string, boolean>>({});
function toggleSection(key: string) {
  expandedSections.value = { ...expandedSections.value, [key]: !expandedSections.value[key] };
}

// 通过 computed 派生，使数据返回后视图能响应式更新（data 为 useQuery 的响应式 ref）
const info = computed(
  () => (data.value as redis_cacheservicev1_RedisCacheMonitorInfo | undefined) ?? undefined,
);
const sections = computed(
  () =>
    (info.value?.sections ?? []) as {
      name: string;
      entries: { key: string; value: string }[];
    }[],
);
const dbSize = computed(() => info.value?.dbSize ?? 0);
const slowlog = computed(
  () => (info.value?.slowlog ?? []) as redis_cacheservicev1_SlowLogEntry[],
);
</script>

<style lang="scss" scoped>
.redis-cache-monitor-page {
  padding: 16px;
}
.card-title {
  font-weight: 600;
}
.section-header {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
}
.toggle-hint {
  font-size: 12px;
  color: var(--el-text-color-secondary);
  margin-left: auto;
}
.entry-value {
  word-break: break-all;
}
.args-cell {
  word-break: break-all;
  white-space: pre-wrap;
}
.disclaimer {
  margin-top: 16px;
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
</style>

// frontend/admin/react/src/pages/app/log/redis-cache-monitor/index.tsx
import { useState } from 'react';
import { Card, Descriptions, Spin, Table, Tag, Typography, Empty, theme } from 'antd';
import type { TableColumnsType } from 'antd';
import { useTranslation } from 'react-i18next';
import type {
  redis_cacheservicev1_RedisCacheMonitorInfo,
  redis_cacheservicev1_SlowLogEntry,
} from '@/api/generated/admin/service/v1';
import { useRedisCacheMonitorInfo } from '@/api/hooks/redis-cache-monitor';
import { formatDateTime } from '@/utils/date';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';

const { Title, Text } = Typography;

/**
 * Redis 缓存监控页面（只读）
 * 展示 Redis INFO（按 section 拆分的键值对）、DBSIZE、SLOWLOG。
 * 数据通过 GET /admin/v1/redis-cache-monitor 拉取，无任何写操作。
 */
const RedisCacheMonitor = () => {
  const { t } = useTranslation('redis-cache-monitor');
  const { token } = theme.useToken();

  const { data, isLoading } = useRedisCacheMonitorInfo();
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({});

  if (isLoading) {
    return (
      <ContentContainer>
        <div style={{ display: 'flex', justifyContent: 'center', padding: 48 }}>
          <Spin size="large" />
        </div>
      </ContentContainer>
    );
  }

  const info = data as redis_cacheservicev1_RedisCacheMonitorInfo | undefined;
  const sections = info?.sections ?? [];
  const dbSize = info?.dbSize ?? 0;
  const slowlog = info?.slowlog ?? [];

  return (
    <ContentContainer>
      {/* 单值指标：DBSIZE */}
      <Card
        size="small"
        style={{ marginBottom: 16 }}
        title={
          <Text strong>
            {t('dbSize')}
          </Text>
        }
      >
        <Descriptions column={1} size="small" bordered colon>
          <Descriptions.Item label={t('dbSize')}>
            <Tag color={dbSize > 0 ? 'orange' : 'default'}>{String(dbSize)}</Tag>
          </Descriptions.Item>
        </Descriptions>
      </Card>

      {/* INFO sections：每个 section 一张可折叠卡片 */}
      {sections.length === 0 ? (
        <Card size="small" style={{ marginBottom: 16 }}>
          <Empty description={t('noInfo')} />
        </Card>
      ) : (
        sections.map((section, idx) => {
          const sectionName = section?.name ?? `${t('section')} ${idx}`;
          const key = `${sectionName}-${idx}`;
          const expanded = expandedSections[key] ?? false;
          return (
            <Card
              key={key}
              size="small"
              style={{ marginBottom: 16 }}
              title={
                <div
                  style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}
                  onClick={() =>
                    setExpandedSections((prev) => ({ ...prev, [key]: !prev[key] }))
                  }
                >
                  <Text strong>{sectionName}</Text>
                  <Tag>{(section?.entries ?? []).length}</Tag>
                  <Text type="secondary" style={{ fontSize: 12 }}>
                    {expanded ? t('collapse') : t('expand')}
                  </Text>
                </div>
              }
            >
              {expanded ? (
                (section?.entries ?? []).length === 0 ? (
                  <Empty description={t('noEntries')} />
                ) : (
                  <Descriptions
                    column={1}
                    size="small"
                    bordered
                    colon
                    contentStyle={{ wordBreak: 'break-all' }}
                    labelStyle={{ width: 240 }}
                  >
                    {(section?.entries ?? []).map((entry, eIdx) => (
                      <Descriptions.Item key={eIdx} label={entry?.key ?? ''}>
                        <span style={{ wordBreak: 'break-all' }}>{entry?.value ?? ''}</span>
                      </Descriptions.Item>
                    ))}
                  </Descriptions>
                )
              ) : (
                <Empty description={t('collapsed')} />
              )}
            </Card>
          );
        })
      )}

      {/* SLOWLOG：静态数据表 */}
      <Card
        size="small"
        title={
          <Text strong>
            {t('slowlog')}
          </Text>
        }
      >
        <Table<redis_cacheservicev1_SlowLogEntry>
          rowKey={(record) => record?.id ?? Math.random()}
          dataSource={slowlog}
          pagination={false}
          size="small"
          scroll={{ x: 'max-content' }}
          locale={{ emptyText: <Empty description={t('noSlowlog')} /> }}
          columns={slowLogColumns(t, token.colorTextSecondary)}
        />
      </Card>

      <Title level={5} type="secondary" style={{ marginTop: 16 }}>
        {t('disclaimer')}
      </Title>
    </ContentContainer>
  );
};

function slowLogColumns(
  t: (key: string) => string,
  _secondaryColor: string,
): TableColumnsType<redis_cacheservicev1_SlowLogEntry> {
  return [
    {
      title: t('slowlogId'),
      dataIndex: 'id',
      width: 80,
    },
    {
      title: t('createdAt'),
      dataIndex: 'createdAt',
      width: 180,
      render: (val) => formatDateTime(val as any),
    },
    {
      title: t('durationUsec'),
      dataIndex: 'durationUsec',
      width: 120,
    },
    {
      title: t('clientAddr'),
      dataIndex: 'clientAddr',
      width: 200,
    },
    {
      title: t('clientName'),
      dataIndex: 'clientName',
      width: 120,
    },
    {
      title: t('args'),
      dataIndex: 'args',
      render: (args: unknown) => {
        const arr = (args as string[] | undefined) ?? [];
        return (
          <span style={{ wordBreak: 'break-all', whiteSpace: 'pre-wrap' }}>
            {arr.join(' ') || '-'}
          </span>
        );
      },
    },
  ];
}

export default RedisCacheMonitor;
