// frontend/admin/vue-vben/apps/admin/src/views/app/log/redis_cache_monitor/index.vue
<script lang="ts" setup>
import { ref } from 'vue';

import { Page } from '@vben/common-ui';
import { $t } from '#/locales';
import { formatDateTime } from '@vben/utils';

import {
  Card,
  Descriptions,
  DescriptionsItem,
  Empty,
  Table,
  Tag,
} from 'ant-design-vue';

import { useRedisCacheMonitorInfo } from '#/api';
import type {
  redis_cacheservicev1_RedisCacheMonitorInfo,
  redis_cacheservicev1_SlowLogEntry,
} from '#/api/generated/admin/service/v1';

const { data, isLoading } = useRedisCacheMonitorInfo();

const expandedSections = ref<Record<string, boolean>>({});
function toggleSection(key: string) {
  expandedSections.value = { ...expandedSections.value, [key]: !expandedSections.value[key] };
}

const info = (data.value as redis_cacheservicev1_RedisCacheMonitorInfo | undefined) ?? undefined;
const sections = (info?.sections ?? []) as {
  name: string;
  entries: { key: string; value: string }[];
}[];
const dbSize = info?.dbSize ?? 0;
const slowlog = (info?.slowlog ?? []) as redis_cacheservicev1_SlowLogEntry[];

const slowLogColumns = [
  {
    title: $t('page.redisCacheMonitor.slowlogId'),
    dataIndex: 'id',
    width: 80,
  },
  {
    title: $t('page.redisCacheMonitor.createdAt'),
    dataIndex: 'createdAt',
    width: 180,
    customRender: ({ text }: { text: unknown }) => formatDateTime(text as any),
  },
  {
    title: $t('page.redisCacheMonitor.durationUsec'),
    dataIndex: 'durationUsec',
    width: 120,
  },
  {
    title: $t('page.redisCacheMonitor.clientAddr'),
    dataIndex: 'clientAddr',
    width: 200,
  },
  {
    title: $t('page.redisCacheMonitor.clientName'),
    dataIndex: 'clientName',
    width: 120,
  },
  {
    title: $t('page.redisCacheMonitor.args'),
    dataIndex: 'args',
  },
];
</script>

<template>
  <Page :auto-content-height="true">
    <div class="redis-cache-monitor-page">
      <Card class="mb-4">
        <template #title>
          <span class="card-title">{{ $t('page.redisCacheMonitor.dbSizeCardTitle') }}</span>
        </template>
        <Descriptions :column="1" bordered>
          <DescriptionsItem :label="$t('page.redisCacheMonitor.dbSize')">
            <Tag :color="dbSize > 0 ? 'orange' : 'default'">{{ String(dbSize) }}</Tag>
          </DescriptionsItem>
        </Descriptions>
      </Card>

      <Card v-if="sections.length === 0" class="mb-4">
        <template #title>
          <span class="card-title">{{ $t('page.redisCacheMonitor.infoCardTitle') }}</span>
        </template>
        <Empty :description="$t('page.redisCacheMonitor.noInfo')" />
      </Card>

      <Card
        v-for="(section, idx) in sections"
        :key="`${section.name}-${idx}`"
        class="mb-4"
      >
        <template #title>
          <div class="section-header" @click="toggleSection(`${section.name}-${idx}`)">
            <span class="card-title">{{ section.name }}</span>
            <Tag>{{ section.entries.length }}</Tag>
            <span class="toggle-hint">
              {{
                expandedSections[`${section.name}-${idx}`]
                  ? $t('page.redisCacheMonitor.collapse')
                  : $t('page.redisCacheMonitor.expand')
              }}
            </span>
          </div>
        </template>
        <Empty
          v-if="!expandedSections[`${section.name}-${idx}`]"
          :description="$t('page.redisCacheMonitor.collapsed')"
        />
        <Empty
          v-else-if="section.entries.length === 0"
          :description="$t('page.redisCacheMonitor.noEntries')"
        />
        <Descriptions v-else :column="1" bordered>
          <DescriptionsItem
            v-for="(entry, eIdx) in section.entries"
            :key="eIdx"
            :label="entry.key"
          >
            <span class="entry-value">{{ entry.value }}</span>
          </DescriptionsItem>
        </Descriptions>
      </Card>

      <Card>
        <template #title>
          <span class="card-title">{{ $t('page.redisCacheMonitor.slowlogCardTitle') }}</span>
        </template>
        <Empty
          v-if="slowlog.length === 0"
          :description="$t('page.redisCacheMonitor.noSlowlog')"
        />
        <Table
          v-else
          :columns="slowLogColumns"
          :data-source="slowlog"
          :pagination="false"
          row-key="id"
          size="small"
        />
      </Card>

      <div class="disclaimer">{{ $t('page.redisCacheMonitor.disclaimer') }}</div>
    </div>
  </Page>
</template>

<style scoped>
.redis-cache-monitor-page {
  padding: 16px;
}
.card-title {
  font-weight: 600;
}
.section-header {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
}
.toggle-hint {
  font-size: 12px;
  color: var(--text-color-secondary, #999);
  margin-left: auto;
}
.entry-value {
  word-break: break-all;
}
.disclaimer {
  margin-top: 16px;
  font-size: 12px;
  color: var(--text-color-secondary, #999);
}
</style>

// frontend/admin/react/src/pages/app/log/redis-cache-monitor/index.tsx
import { useState } from 'react';
import { Card, Descriptions, Spin, Table, Tag, Typography, Empty, theme } from 'antd';
import type { TableColumnsType } from 'antd';
import { useTranslation } from 'react-i18next';
import type {
  redis_cacheservicev1_RedisCacheMonitorInfo,
  redis_cacheservicev1_SlowLogEntry,
} from '@/api/generated/admin/service/v1';
import { useRedisCacheMonitorInfo } from '@/api/hooks/redis-cache-monitor';
import { formatDateTime } from '@/utils/date';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';

const { Title, Text } = Typography;

/**
 * Redis 缓存监控页面（只读）
 * 展示 Redis INFO（按 section 拆分的键值对）、DBSIZE、SLOWLOG。
 * 数据通过 GET /admin/v1/redis-cache-monitor 拉取，无任何写操作。
 */
const RedisCacheMonitor = () => {
  const { t } = useTranslation('redis-cache-monitor');
  const { token } = theme.useToken();

  const { data, isLoading } = useRedisCacheMonitorInfo();
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({});

  if (isLoading) {
    return (
      <ContentContainer>
        <div style={{ display: 'flex', justifyContent: 'center', padding: 48 }}>
          <Spin size="large" />
        </div>
      </ContentContainer>
    );
  }

  const info = data as redis_cacheservicev1_RedisCacheMonitorInfo | undefined;
  const sections = info?.sections ?? [];
  const dbSize = info?.dbSize ?? 0;
  const slowlog = info?.slowlog ?? [];

  return (
    <ContentContainer>
      {/* 单值指标：DBSIZE */}
      <Card
        size="small"
        style={{ marginBottom: 16 }}
        title={
          <Text strong>
            {t('dbSize')}
          </Text>
        }
      >
        <Descriptions column={1} size="small" bordered colon>
          <Descriptions.Item label={t('dbSize')}>
            <Tag color={dbSize > 0 ? 'orange' : 'default'}>{String(dbSize)}</Tag>
          </Descriptions.Item>
        </Descriptions>
      </Card>

      {/* INFO sections：每个 section 一张可折叠卡片 */}
      {sections.length === 0 ? (
        <Card size="small" style={{ marginBottom: 16 }}>
          <Empty description={t('noInfo')} />
        </Card>
      ) : (
        sections.map((section, idx) => {
          const sectionName = section?.name ?? `${t('section')} ${idx}`;
          const key = `${sectionName}-${idx}`;
          const expanded = expandedSections[key] ?? false;
          return (
            <Card
              key={key}
              size="small"
              style={{ marginBottom: 16 }}
              title={
                <div
                  style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}
                  onClick={() =>
                    setExpandedSections((prev) => ({ ...prev, [key]: !prev[key] }))
                  }
                >
                  <Text strong>{sectionName}</Text>
                  <Tag>{(section?.entries ?? []).length}</Tag>
                  <Text type="secondary" style={{ fontSize: 12 }}>
                    {expanded ? t('collapse') : t('expand')}
                  </Text>
                </div>
              }
            >
              {expanded ? (
                (section?.entries ?? []).length === 0 ? (
                  <Empty description={t('noEntries')} />
                ) : (
                  <Descriptions
                    column={1}
                    size="small"
                    bordered
                    colon
                    contentStyle={{ wordBreak: 'break-all' }}
                    labelStyle={{ width: 240 }}
                  >
                    {(section?.entries ?? []).map((entry, eIdx) => (
                      <Descriptions.Item key={eIdx} label={entry?.key ?? ''}>
                        <span style={{ wordBreak: 'break-all' }}>{entry?.value ?? ''}</span>
                      </Descriptions.Item>
                    ))}
                  </Descriptions>
                )
              ) : (
                <Empty description={t('collapsed')} />
              )}
            </Card>
          );
        })
      )}

      {/* SLOWLOG：静态数据表 */}
      <Card
        size="small"
        title={
          <Text strong>
            {t('slowlog')}
          </Text>
        }
      >
        <Table<redis_cacheservicev1_SlowLogEntry>
          rowKey={(record) => record?.id ?? Math.random()}
          dataSource={slowlog}
          pagination={false}
          size="small"
          scroll={{ x: 'max-content' }}
          locale={{ emptyText: <Empty description={t('noSlowlog')} /> }}
          columns={slowLogColumns(t, token.colorTextSecondary)}
        />
      </Card>

      <Title level={5} type="secondary" style={{ marginTop: 16 }}>
        {t('disclaimer')}
      </Title>
    </ContentContainer>
  );
};

function slowLogColumns(
  t: (key: string) => string,
  _secondaryColor: string,
): TableColumnsType<redis_cacheservicev1_SlowLogEntry> {
  return [
    {
      title: t('slowlogId'),
      dataIndex: 'id',
      width: 80,
    },
    {
      title: t('createdAt'),
      dataIndex: 'createdAt',
      width: 180,
      render: (val) => formatDateTime(val as any),
    },
    {
      title: t('durationUsec'),
      dataIndex: 'durationUsec',
      width: 120,
    },
    {
      title: t('clientAddr'),
      dataIndex: 'clientAddr',
      width: 200,
    },
    {
      title: t('clientName'),
      dataIndex: 'clientName',
      width: 120,
    },
    {
      title: t('args'),
      dataIndex: 'args',
      render: (args: unknown) => {
        const arr = (args as string[] | undefined) ?? [];
        return (
          <span style={{ wordBreak: 'break-all', whiteSpace: 'pre-wrap' }}>
            {arr.join(' ') || '-'}
          </span>
        );
      },
    },
  ];
}

export default RedisCacheMonitor;
